### ISSUE TITLE
You called `.test()` without defining model's `.test_step()` 

### ISSUE THREAD

**Issue by applech666** [felixkreuk/Phoneme-Boundary-Detection-using-Learnable-Segmental-Features#1]
hi, felixkreuk! Thank you for sharing your research results!
I had a problem in the test.

Traceback (most recent call last):
  File "main.py", line 122, in <module>
    main(args)
  File "main.py", line 67, in main
    trainer.test(solver)
  File "/home/research/anaconda3/envs/phoneme_torch1.4/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 857, in test
    self.fit(model)
  File "/home/research/anaconda3/envs/phoneme_torch1.4/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 692, in fit
    self.dp_train(model)
  File "/home/research/anaconda3/envs/phoneme_torch1.4/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 471, in dp_train
    self.run_pretrain_routine(model)
  File "/home/research/anaconda3/envs/phoneme_torch1.4/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 790, in run_pretrain_routine
    self.run_evaluation(test=True)
  File "/home/research/anaconda3/envs/phoneme_torch1.4/lib/python3.6/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 273, in run_evaluation
    raise MisconfigurationException(m)
pytorch_lightning.utilities.debugging.MisconfigurationException: You called `.test()` without defining model's `.test_step()` or `.test_end()`.
                    Please define and try again

**Comment by Coice** [comment]
@applech666  Were you able to resolve this? I am getting the same error. @felixkreuk

**Comment by applech666** [comment]
@coice Yes, I added a definition to solver.py. As follows:

    def test_end(self, outputs):
        return self.generic_eval_end(outputs, 'test')
you can try!
